# Main application configuration file.
#
# @author TSS

spring:
  profiles:
    active: "invalid"
  h2:
    console:
      enabled: true
      path: "/h2db"
      settings:
        web-allow-others: true
    driver: "org.h2.Driver"
    file: "/data/restbox"
    username: "admin"
    password: "admin"
