# Main application configuration file.
#
# @author TSS

spring:
  profiles:
    active: "invalid"
  datasource:
    url: "jdbc:h2:file:/data/restbox"
    driverClassName: "org.h2.Driver"
    username: "admin"
    password: "admin"
  h2:
    console:
      enabled: true
      path: "/h2db"
      settings:
        web-allow-others: true
