# Main application configuration file.
#
# @author TSS

spring:
  profiles:
    active: "invalid"
  h2:
    console:
      enabled: true
      path: "/h2db"
      settings:
        web-allow-others: true
    file: "/data/restbox"
    username: "admin"
    password: "admin"
    migrations:
      - "/h2/init-1.0.0.sql"

rest-api:
  lang: "en"
